import cv2 as cv
import numpy as np
img = cv.imread(r"C:\Users\salwa\Downloads\371533082_1048648173174637_3384000278143686871_n.jpg")
cv.imshow('salwa',img)

b,g,r = cv.split(img)
cv.imshow('blue',b)
cv.imshow('green',g)
cv.imshow('red',r)
print(img.shape)
print(b.shape)
print(g.shape)
print(r.shape)
print("version 15")
merged = cv.merge([b,g,r])
blank = np.zeros(img.shape[:2], dtype='uint8')
blue = cv.merge([b,blank,blank])
red = cv.merge([blank,blank,r])
cv.imshow('bluee',blue)
cv.imshow('Merged Image', merged)
cv.waitKey(0)